apiVersion: v1
kind: Service
metadata:
  name: student-dashboard-svc
spec:
  # Use NodePort for local access (Minikube, etc.)
  # Docker Desktop can often handle LoadBalancer, but NodePort is more universal.
  type: NodePort
  selector:
    app: student-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # The NodePort will be assigned automatically by Kubernetes (e.g., 30000-32767)